server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # 1. Obsługa aplikacji Angular (Frontend)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Backend - Departments
    location /departments {
        # host.docker.internal pozwala połączyć się z localhostem Twojego komputera
        proxy_pass http://backend-department:8081;
        
        # Nagłówki, żeby backend wiedział skąd przyszło zapytanie (odpowiednik changeOrigin: true)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Backend - Scientists
    location /scientists {
        proxy_pass http://backend-scientist:8082;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Cache plików statycznych
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000";
    }
}