### api wydzialow -------------------------------------------------

### Dodaj department
POST http://localhost:8080/departments
Content-Type: application/json

{
  "departmentName": "wydzial testowy",
  "departmentBuildingNumber": 10
}

### update departamentu
PUT http://localhost:8081/departments/fe3e6021-a6a7-33d4-8f7b-dd06d000bba9
Content-Type: application/json

{
  "departmentName": "wydzial testowy",
  "departmentBuildingNumber": 10
}

### Pobierz wszystkie departamenty
GET http://localhost:8082/departments

### Pobierz wybrany wydzial
GET http://localhost:8080/departments/fe3e6021-a6a7-33d4-8f7b-dd06d000bba9

### Pobierz wydzial ktory nie istnieje
GET http://localhost:8080/departments/fe3e6021-a6a7-33d4-8f7b-dd06d000bba

### Usun wydzial
DELETE http://localhost:8080/departments/fe3e6021-a6a7-33d4-8f7b-dd06d000bba9

### api pracownikow -------------------------------------------------

### Pobierz pracowników
GET http://localhost:8080/scientists

### Pobierz pracownika (trzeba wybrac id)
GET http://localhost:8080/scientists/06fa4922-60ba-42f7-8e92-e2d7e1569d00

### Pobierz pracownika zle id
GET http://localhost:8080/scientists/06fa4922-60ba-42f7-8e92-e2d7e1569d0

### Dodaj pracownika
POST http://localhost:8080/scientists
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test1",
  "degree": "test",
  "age": 41,
  "departmentName": "Wydzial Elektroniki Teleinformatyki i Informatyki"
}

### Usun pracownika
DELETE http://localhost:8080/scientists/3611357e-0d12-4b0e-abfd-cf9e9e2dba54

### Pobierz pracownikow wydzialu
GET http://localhost:8080/scientists/dep/fe3e6021-a6a7-33d4-8f7b-dd06d000bba9

### update
PUT http://localhost:8080/scientists/c9d53e62-8e96-497b-846c-54ffc7b83936
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test1",
  "degree": "test",
  "age": 41,
  "departmentName": "Wydzial Elektroniki Teleinformatyki i Informatyki"
}
