spring.application.name=lab3

server.port=8081
# --------------------------------------------------------------
# database settings copied from lecture "02 Spring Data JPA.pdf"

# Data source settings:
#spring.datasource.url=jdbc:h2:mem:simple-rpg
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=password
#
## JPA settings:
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.generate-ddl=true
#
## Hibernate specific settings:
#spring.jpa.hibernate.ddl-auto=update
#
## H2 specific settings:
#spring.h2.console.enabled=true
## Ustawia ?cie?k? (domy?lnie jest /h2-console, ale warto wpisa? jawnie)
#spring.h2.console.path=/h2-console

# --------------------------------------------------------------

